# Generated by Django 2.2.5 on 2019-09-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkateBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=70)),
                ('brand', models.CharField(max_length=70)),
                ('weight', models.FloatField()),
                ('location', models.CharField(max_length=70)),
            ],
        ),
    ]
