# Generated by Django 2.2.5 on 2019-09-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190911_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='skateboard',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
