/*Inserting default values in the db on startup*/
INSERT INTO SKATEBOARD (ID, BRAND, IS_BOARD_AVAILABLE, LENGTH, LOCATION, OWNER_NAME, WEIGHT)
VALUES (1, 'TEST', TRUE, 30, 'LOCATION1', 'OWNER', 40);

INSERT INTO SKATEBOARD (ID, BRAND, IS_BOARD_AVAILABLE, LENGTH, LOCATION, OWNER_NAME, WEIGHT)
VALUES (2, 'TEST2', FALSE, 30, 'LOCATION2', 'OWNER2', 45);